apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      containers:
        - name: krill
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config
            - {{ .Values.config.path }}
          ports:
            - containerPort: {{ .Values.service.httpPort }}
              name: http
            - containerPort: {{ .Values.service.webhookPort }}
              name: webhook
          volumeMounts:
            - name: config
              mountPath: /etc/krill
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
